[package]
authors = ["Abdun Nihaal <nifey@users.noreply.github.com>"]
name = "road_rash_o"
version = "0.1.0"
[dependencies]
piston = "0.35.0"
piston2d-graphics = "0.23.0"
piston2d-opengl_graphics = "0.49.0"
pistoncore-glutin_window = "0.42.0"
